name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2
      - uses: abhinavsingh/setup-bazel@v3

      # - name: Install Visual C++ for Python 2.7
      #   if: runner.os == 'Windows'
      #   run: choco install vcpython27 -f -y

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: "stellaraccident/manylinux2014_x86_64-bazel-3.7.2:latest"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD: "cp3*-*"
          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}